force-app/main/default/objects/CB_Item__c/CB_Item__c.object-meta.xml
<CustomObject>
    <label>CB Item</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>CB Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CB Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CB_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CB Items</relationshipLabel>
    <relationshipName>CB_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CB_Item__c/fields/CB_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Item_Id__c</fullName>
    <label>CB Item Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CB_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CB Items</relationshipLabel>
    <relationshipName>CB_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/Chargebee_Event__c.object-meta.xml
<CustomObject>
    <label>Chargebee Event</label>
    <nameField>
        <displayFormat>CB-Event{0000}</displayFormat>
        <label>Chargebee Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chargebee Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chargebee_Event__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chargebee Events</relationshipLabel>
    <relationshipName>Chargebee_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Customer_Id__c</fullName>
    <label>CB Customer Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Event_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Event_Id__c</fullName>
    <label>CB Event Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>CB_Event_Type__c</fullName>
    <label>CB Event Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Invoice_Id__c</fullName>
    <label>CB Invoice Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Subscription_Id__c</fullName>
    <label>CB Subscription Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Chargebee Events</relationshipLabel>
    <relationshipName>Chargebee_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChargebeeEventREST.cls
/**
* @author: Solved by Software, Co
*/

@RestResource(urlMapping='/ChargebeeEvent/*')
global class ChargebeeEventREST {
    @HttpPost
    global static void doPost() {
        RestRequest req = RestContext.request; 
        RestResponse res = RestContext.response;
        if(req.requestBody != null) {
            //1. Save the raw JSON to Log__c with Description = 'Event from Chargebee'
            string json = req.requestBody.toString();
            System.debug('Request body: ' + json);
            Log__c log = Logger.CreateLog(json, null, 'Incoming Webhook', 'Event from Chargebee', false, null);
            //2. try to parse JSON to ChargebeeEvent class APEX class
            try {
                ChargebeeEvent obj = ChargebeeEvent.parse(json);
                System.debug(obj.content.invoice.id);
                //3. Create a Chargebee_Event__c record
                Chargebee_Event__c evet = new Chargebee_Event__c();
                List<CB_Item__c> cbItems = [SELECT Id, Account__c, Opportunity__c 
                                            FROM CB_Item__c
                                            WHERE CB_Item_Id__c = :obj.content.invoice.id];
                if(cbItems.size() > 0) {
                    CB_Item__c cbItem = cbItems[0];
                    evet.CB_Event_Type__c = obj.event_type;
                    evet.CB_Event_Id__c = obj.id;
                    evet.CB_Subscription_Id__c = obj.content.subscription != null ? obj.content.subscription.id : null;
                    evet.CB_Customer_Id__c = obj.content.customer != null ? obj.content.customer.id : null;
                    evet.CB_Invoice_Id__c = obj.content.invoice != null ? obj.content.invoice.id : null;
                    evet.Account__c = cbItem.Account__c;
                    evet.Opportunity__c = cbItem.Opportunity__c;
                    //Only save if the event is not related to a subscription
                    if(evet.CB_Subscription_Id__c == null) {
	                    insert evet;       
                    }
                }
            } catch (Exception ex) {
                log.Error__c = true;
                log.Error_Message__c = ex.getMessage();
            }
            insert log;            
        }
    }
    @HttpGet
    global static string Ping() {
        return 'Alive';
    }
}