force-app/main/default/objects/Chargebee_Event__c/Chargebee_Event__c.object-meta.xml
<CustomObject>
    <label>Chargebee Event</label>
    <nameField>
        <displayFormat>CB-Event{0000}</displayFormat>
        <label>Chargebee Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chargebee Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chargebee_Event__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chargebee Events</relationshipLabel>
    <relationshipName>Chargebee_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Customer_Id__c</fullName>
    <label>CB Customer Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Event_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Event_Id__c</fullName>
    <label>CB Event Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>CB_Event_Type__c</fullName>
    <label>CB Event Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Invoice_Id__c</fullName>
    <label>CB Invoice Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/CB_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>CB_Subscription_Id__c</fullName>
    <label>CB Subscription Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Chargebee Events</relationshipLabel>
    <relationshipName>Chargebee_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/To_be_Processed__c.field-meta.xml
<CustomField>
    <fullName>To_be_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>To be Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProcessChargebeeEventBatch.cls
/**
* @author: Solved by Software, Co
*/

global class ProcessChargebeeEventBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext BC) {        
        String query = 'SELECT Id, Account__c, CB_Customer_Id__c, CB_Event_Id__c, ' +
	                    'CB_Event_Type__c, CB_Invoice_Id__c, CB_Subscription_Id__c, Opportunity__c, ' +
	                    'Processed__c, To_be_Processed__c ' +
                        'FROM Chargebee_Event__c ' +
                        'WHERE Processed__c = false';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<Chargebee_Event__c> events) {
        for(Chargebee_Event__c evet : events){
            evet.To_be_Processed__c = true;
        }
        update events;
    }
    public void finish(Database.BatchableContext BC) {
        system.debug('==========ProcessChargebeeEventBatch=====');
    }
}