force-app/main/default/objects/Chargebee_Event__c/Chargebee_Event__c.object-meta.xml
<CustomObject>
    <label>Chargebee Event</label>
    <nameField>
        <displayFormat>CB-Event{0000}</displayFormat>
        <label>Chargebee Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chargebee Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chargebee_Event__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chargebee Events</relationshipLabel>
    <relationshipName>Chargebee_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chargebee_Event__c/fields/To_be_Processed__c.field-meta.xml
<CustomField>
    <fullName>To_be_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>To be Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProcessChargebeeEventSchedulerTest.cls
/**
* @author: Solved by Software, Co
*/

@isTest
public class ProcessChargebeeEventSchedulerTest {
	@TestSetup
    public static void makeData(){
        Account objAccount = new Account();
        objAccount.Name = 'Test';
        objAccount.Phone = '111-222-3333';
        insert objAccount;
        
        Chargebee_Event__c objChargebeeEvent = new Chargebee_Event__c();
        objChargebeeEvent.Account__c=objAccount.Id;
        objChargebeeEvent.Processed__c=false;
        objChargebeeEvent.To_be_Processed__c=false;
        insert objChargebeeEvent;
    }
    @isTest
    public static void processChargebeeEventTest(){
        Chargebee_Event__c objChargebeeEvent = [SELECT To_be_Processed__c FROM Chargebee_Event__c LIMIT 1];
        System.assertEquals(false,objChargebeeEvent.To_be_Processed__c);
        
        Test.startTest();
        ProcessChargebeeEventScheduler sch = new ProcessChargebeeEventScheduler();
        sch.execute(null);
        Test.stopTest();
        
        objChargebeeEvent = [SELECT To_be_Processed__c FROM Chargebee_Event__c LIMIT 1];
        System.assertEquals(true,objChargebeeEvent.To_be_Processed__c);
    }
}