force-app/main/default/objects/Chargebee_Setting__mdt/Chargebee_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Chargebee Setting</label>
    <pluralLabel>Chargebee Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Resume_Subscription_Url__c.field-meta.xml
<CustomField>
    <fullName>Resume_Subscription_Url__c</fullName>
    <label>Resume Subscription Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ChargebeeAPIField__mdt/ChargebeeAPIField__mdt.object-meta.xml
<CustomObject>
    <label>Chargebee API Field</label>
    <pluralLabel>Chargebee API Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/ChargebeeAPIField__mdt/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancel Subscription</fullName>
                <default>true</default>
                <label>Cancel Subscription</label>
            </value>
            <value>
                <fullName>Pause Subscription with Date</fullName>
            </value>
            <value>
                <fullName>Pause Subscription without Date</fullName>
            </value>
            <value>
                <fullName>Resume Subscription</fullName>
            </value>
            <value>
                <fullName>Update Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChargebeeResumeSubscriptionInvocable.cls
/**
* @author: Solved by Software, Co
*/
global class ChargebeeResumeSubscriptionInvocable {
    @InvocableMethod(Label='Resume Subscription') 
    public static void ResumeCBSubscription(List<ChargebeeInvocableRequest> reqs) {
        Chargebee_Setting__mdt chargebeeSetting = ChargebeeHierarchyInvocable.GetCBSetting();
        List<ChargebeeAPIField__mdt> ChargebeeAPIFields = [SELECT Id, Key__c, Value__c FROM ChargebeeAPIField__mdt
                                                            WHERE API_Name__c = 'Resume Subscription'];
        String body = '';
        for(ChargebeeAPIField__mdt singleChargebeeAPIField:ChargebeeAPIFields){
            body += new ChargebeeController().setValue(singleChargebeeAPIField.Key__c, singleChargebeeAPIField.Value__c);    
        }
        body = body.substringBeforeLast('&');
        for(ChargebeeInvocableRequest req : reqs) {
            DoCallOut(chargebeeSetting.Resume_Subscription_Url__c.replace('{{SubscriptionId}}', req.cbSubscriptionId), body, 'POST', 'Resume CB Subscription for Account: ' + req.accountId);
        }
    } 
    @Future(callout=true)
    public static void DoCallOut(String URL, String body, String method, String logDescription) {
        new ChargebeeController().doCallOut(URL, body, method, logDescription);
    }
}