force-app/main/default/objects/Chargebee_Setting__mdt/Chargebee_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Chargebee Setting</label>
    <pluralLabel>Chargebee Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Pause_Subscription_Url__c.field-meta.xml
<CustomField>
    <fullName>Pause_Subscription_Url__c</fullName>
    <label>Pause Subscription Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ChargebeeAPIField__mdt/ChargebeeAPIField__mdt.object-meta.xml
<CustomObject>
    <label>Chargebee API Field</label>
    <pluralLabel>Chargebee API Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/ChargebeeAPIField__mdt/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancel Subscription</fullName>
                <default>true</default>
                <label>Cancel Subscription</label>
            </value>
            <value>
                <fullName>Pause Subscription with Date</fullName>
            </value>
            <value>
                <fullName>Pause Subscription without Date</fullName>
            </value>
            <value>
                <fullName>Resume Subscription</fullName>
            </value>
            <value>
                <fullName>Update Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChargebeePauseSubscriptionInvocable.cls
/**
* @author: Solved by Software, Co
*/
global class ChargebeePauseSubscriptionInvocable {
    @InvocableMethod(Label='Pause Subscription') 
    public static void PauseCBSubscription(List<ChargebeeInvocableRequest> reqs) {
        Chargebee_Setting__mdt chargebeeSetting = ChargebeeHierarchyInvocable.GetCBSetting();
        List<ChargebeeAPIField__mdt> ChargebeeAPIFields = [SELECT Id, Key__c, Value__c FROM ChargebeeAPIField__mdt
                                                            WHERE API_Name__c = 'Pause Subscription without Date'];
        String body = '';
        for(ChargebeeAPIField__mdt singleChargebeeAPIField:ChargebeeAPIFields){
            body +=  new ChargebeeController().setValue(singleChargebeeAPIField.Key__c, singleChargebeeAPIField.Value__c);    
        }
        body = body.substringBeforeLast('&');
        for(ChargebeeInvocableRequest req : reqs) {
            ChargebeeResumeSubscriptionInvocable.doCallOut(chargebeeSetting.Pause_Subscription_Url__c.replace('{{SubscriptionId}}', req.cbSubscriptionId), body, 'POST', 'Pause CB Subscription for Account: ' + req.accountId);
        }
    }
}