force-app/main/default/objects/CB_Cus_Created__e/CB_Cus_Created__e.object-meta.xml
<CustomObject>
    <label>CB Cus Created</label>
    <pluralLabel>CB Cus Created</pluralLabel>
</CustomObject>

force-app/main/default/objects/CB_Cus_Created__e/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <description>Unique field for platform event</description>
    <label>GUID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/Chargebee_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Chargebee Setting</label>
    <pluralLabel>Chargebee Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Cancel_Subscription_Url__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Subscription_Url__c</fullName>
    <label>Cancel Subscription Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Charge_Bee_Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bee_Site_Name__c</fullName>
    <label>Charge Bee Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <defaultValue>&quot;application/x-www-form-urlencoded&quot;</defaultValue>
    <label>ContentType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Create_Customer_Url__c.field-meta.xml
<CustomField>
    <fullName>Create_Customer_Url__c</fullName>
    <label>Create Customer Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Create_Invoice_Url__c.field-meta.xml
<CustomField>
    <fullName>Create_Invoice_Url__c</fullName>
    <label>Create Invoice Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Create_Subscription_Url__c.field-meta.xml
<CustomField>
    <fullName>Create_Subscription_Url__c</fullName>
    <label>Create Subscription Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Days_to_delay_location_invoice__c.field-meta.xml
<CustomField>
    <fullName>Days_to_delay_location_invoice__c</fullName>
    <label>Days to delay location invoice</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Days_to_delay_location_sub_start__c.field-meta.xml
<CustomField>
    <fullName>Days_to_delay_location_sub_start__c</fullName>
    <label>Days to delay location sub start</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Days_to_delay_parent_invoice__c.field-meta.xml
<CustomField>
    <fullName>Days_to_delay_parent_invoice__c</fullName>
    <label>Days to delay parent invoice</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Delete_Hierarchy_Url__c.field-meta.xml
<CustomField>
    <fullName>Delete_Hierarchy_Url__c</fullName>
    <label>Delete Hierarchy Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Pause_Subscription_Url__c.field-meta.xml
<CustomField>
    <fullName>Pause_Subscription_Url__c</fullName>
    <label>Pause Subscription Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Resume_Subscription_Url__c.field-meta.xml
<CustomField>
    <fullName>Resume_Subscription_Url__c</fullName>
    <label>Resume Subscription Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Retrieve_Invoice_as_PDF_URL__c.field-meta.xml
<CustomField>
    <fullName>Retrieve_Invoice_as_PDF_URL__c</fullName>
    <label>Retrieve Invoice as PDF URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Set_Hierarchy_Url__c.field-meta.xml
<CustomField>
    <fullName>Set_Hierarchy_Url__c</fullName>
    <label>Set Hierarchy Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Update_Customer_Url__c.field-meta.xml
<CustomField>
    <fullName>Update_Customer_Url__c</fullName>
    <label>Update Customer Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Update_Subscription_Url__c.field-meta.xml
<CustomField>
    <fullName>Update_Subscription_Url__c</fullName>
    <label>Update Subscription Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Chargebee_Setting__mdt/fields/Void_Invoice_Url__c.field-meta.xml
<CustomField>
    <fullName>Void_Invoice_Url__c</fullName>
    <label>Void Invoice Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ChargebeeHierarchyInvocable.cls
/**
* @author: Solved by Software, Co
*/

global class ChargebeeHierarchyInvocable {
    public static Chargebee_Setting__mdt getChargebeeSettingTest(){
        List<Chargebee_Setting__mdt> chargebeeSettings = new List<Chargebee_Setting__mdt>();
        Chargebee_Setting__mdt chargebeeSetting = new Chargebee_Setting__mdt();
        chargebeeSetting.Create_Customer_Url__c='https://mytest.chargebee.com/api/v2/customers';
        chargebeeSetting.Update_Customer_Url__c='https://mytest.chargebee.com/api/v2/customers/{{CustomerId}}';
        chargebeeSetting.ContentType__c='';
        chargebeeSetting.Private_Key__c='thisisprivatekey';                                                            
        chargebeeSetting.Create_Subscription_Url__c='https://mytest.chargebee.com/api/v2/customers/{{CustomerId}}/subscription_for_items';
        chargebeeSetting.Set_Hierarchy_Url__c='https://mytest.chargebee.com/api/v2/customers/{{CustomerId}}/relationships';
        chargebeeSetting.Create_Invoice_Url__c='https://mytest.chargebee.com/api/v2/invoices/create_for_charge_items_and_charges';                                                            
        chargebeeSetting.Cancel_Subscription_Url__c='https://mytest.chargebee.com/api/v2/subscriptions/{{SubscriptionId}}/cancel_for_items';
        chargebeeSetting.Pause_Subscription_Url__c='https://mytest.chargebee.com/api/v2/subscriptions/{{SubscriptionId}}/pause';
        chargebeeSetting.Resume_Subscription_Url__c='https://mytest.chargebee.com/api/v2/subscriptions/{{SubscriptionId}}/resume';
        chargebeeSetting.Update_Subscription_Url__c='https://mytest.chargebee.com/api/v2/subscriptions/{{SubscriptionId}}/update_for_items';
        chargebeeSetting.Delete_Hierarchy_Url__c='https://incentivio-test.chargebee.com/api/v2/customers/{{CustomerId}}//delete_relationship';
        chargebeeSetting.Set_Hierarchy_Url__c='https://incentivio-test.chargebee.com/api/v2/customers/{{CustomerId}}/relationships';
        chargebeeSetting.Retrieve_Invoice_as_PDF_URL__c = 'https://incentivio-test.chargebee.com/api/v2/invoices/{{invoice-id}}/pdf';
        chargebeeSetting.Charge_Bee_Site_Name__c='test-incentivio-chargebee';
        chargebeeSetting.Days_to_delay_parent_invoice__c=0;
        chargebeeSetting.Days_to_delay_location_invoice__c=0;
        chargebeeSetting.Days_to_delay_location_sub_start__c=0;
        chargebeeSetting.Void_Invoice_Url__c='https://incentivio-test.chargebee.com/api/v2/invoices/{{invoice-id}}/void';
        return chargebeeSetting;
    }
    public static Chargebee_Setting__mdt GetCBSetting() {
        boolean runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
        String env = runningInASandbox?'Sandbox':'Production';
        return Test.isRunningTest()?getChargebeeSettingTest():Chargebee_Setting__mdt.getInstance(env);
    }
    private static string buildHierarchyPayload(Account parentAcct, Account objAccount, String action) {
        String body = '';
        body = 'parent_id='+parentAcct.chargebeeapps__CB_Id__c;
        boolean delaySetParentAsPayer = false;
        //If the monthly should be paid by parent and the setup fees should be paid by location, delay setting the parent as payer until after the setup invoice is paid
        if(action == 'Create' && objAccount.Monthly_Fees_Paid_by_Parent__c == true && objAccount.Paid_by_Parent__c == false) {
            delaySetParentAsPayer = true;
        }
        if(objAccount.Monthly_Fees_Paid_by_Parent__c && delaySetParentAsPayer == false) {
            body += '&payment_owner_id='+parentAcct.chargebeeapps__CB_Id__c;
            body += '&invoice_owner_id='+parentAcct.chargebeeapps__CB_Id__c;            
        } else {
            body += '&payment_owner_id='+objAccount.chargebeeapps__CB_Id__c;
            body += '&invoice_owner_id='+objAccount.chargebeeapps__CB_Id__c;      
        }
        return body;
    }
    @future(callout = true)
    public static void CallCBRecreateeHierarchy(List<Id> parentIds, List<Id> childIds) {
        List<Log__c> logs = new List<Log__c>();
        Chargebee_Setting__mdt chargebeeSetting = GetCBSetting();
        Httprequest req = new HttpRequest();
        Account objAccount= FetchAccount(childIds[0]);
        Account parentAcct = FetchAccount(parentIds[0]);
        System.debug('CC: ' + objAccount.chargebeeapps__CB_Id__c);
        req.setEndpoint(chargebeeSetting.Delete_Hierarchy_Url__c.replace('{{CustomerId}}', objAccount.chargebeeapps__CB_Id__c));
        req.setMethod('POST');
        req.setHeader('Content-Type','application/x-www-form-urlencoded');
        Blob headerValue = Blob.valueOf(chargebeeSetting.Private_Key__c);
        String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);
        logs.add(logger.CreateLogFromRequest(req, 'Callout', 'Delete Hierarchy for: ' + childIds[0]));

        req.setEndpoint(chargebeeSetting.Set_Hierarchy_Url__c.replace('{{CustomerId}}', objAccount.chargebeeapps__CB_Id__c));
        String body = buildHierarchyPayload(parentAcct,  objAccount, 'Recreate');
        req.setBody(body);

        logs.add(logger.CreateLogFromRequest(req, 'Callout', 'Create Hierarchy for: ' + childIds[0])); 
        insert logs;
    }
    public static ChargebeeInvocableRequest CallCBCreateHierarchy(Account objAccount, Account parentAcct, String eventId) {
        List<Log__c> logs = new List<Log__c>();
        ChargebeeInvocableRequest r = new ChargebeeInvocableRequest();
        Chargebee_Setting__mdt chargebeeSetting = GetCBSetting();
        Httprequest req = new HttpRequest();
        req.setEndpoint(chargebeeSetting.Set_Hierarchy_Url__c.replace('{{CustomerId}}', objAccount.chargebeeapps__CB_Id__c));
        req.setMethod('POST');
        req.setHeader('Content-Type','application/x-www-form-urlencoded');
        Blob headerValue = Blob.valueOf(chargebeeSetting.Private_Key__c);
        String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);

        String body = buildHierarchyPayload(parentAcct,  objAccount, 'Create');
        req.setBody(body);
        
        logs.add(logger.CreateLogFromRequest(req, 'Callout', chargebeeSetting.Set_Hierarchy_Url__c.replace('{{CustomerId}}', objAccount.chargebeeapps__CB_Id__c))); 
        
        r.logs = logs;

        List<CB_Cus_Created__e> cusEvents = new List<CB_Cus_Created__e>();
        cusEvents.add(new CB_Cus_Created__e(GUID__c = eventId));
        List<Database.SaveResult> results = EventBus.publish(cusEvents);
        return r;
    }
    private static Account FetchAccount(Id acctId) {
        System.debug('FetchAccount: ' + acctId);
        return [SELECT Id, chargebeeapps__CB_Id__c, Paid_By_Parent__c, Monthly_Fees_Paid_by_Parent__c
                FROM Account
                WHERE Id = :acctId
                LIMIT 1];
    }
    @InvocableMethod(Label='Chargebee Hierarchy')
    public static List<ChargebeeInvocableRequest> createHierarchy(List<ChargebeeInvocableRequest> reqs) {
        System.debug('createHierarchy: ' + reqs);
        List<ChargebeeInvocableRequest> rs = new List<ChargebeeInvocableRequest>();
        ChargebeeInvocableRequest r = new ChargebeeInvocableRequest();
        ChargebeeInvocableRequest req = reqs[0];
        List<Id> parentIds = new List<Id>();
        parentIds.add(req.parentId);
        List<Id> childIds = new List<Id>();
        childIds.add(req.childId);
        if(req.action == 'Create') {
            r = CallCBCreateHierarchy(req.acctObj, req.parentAcct, req.EventId);
            rs.add(r);
        } else {
            CallCBRecreateeHierarchy(parentIds, childIds);
        }
        List<CB_Cus_Created__e> cusEvents = new List<CB_Cus_Created__e>();
        cusEvents.add(new CB_Cus_Created__e(GUID__c = reqs[0].EventId));
        List<Database.SaveResult> results = EventBus.publish(cusEvents);
        return rs;
    }
}